#!/usr/bin/env python

from setuptools import setup, find_packages
import os

MAJOR               = 0
MINOR               = 1
MICRO               = 0
ISRELEASED          = False
VERSION             = '%d.%d.%d' % (MAJOR, MINOR, MICRO)

MODULE_PATH = os.path.dirname(os.path.abspath(__file__))

config = ['# Autogenerated config file using crow.conf\n']

user_config = os.path.join(MODULE_PATH, 'crow.conf')

if os.path.isfile(user_config):
    with open(user_config) as f:
        for line in f:
            line = line.replace('$CROW_HOME', MODULE_PATH)
            config.append(line)

config_file = os.path.join('crow', 'config.py')
print 'config file', config_file, user_config
with open(config_file, 'w') as f:
    for line in config:
        f.write('%s' % line)

reqs = []
if os.path.isfile('requirements.txt'):
    with open('requirements.txt') as f:
        required = f.read().splitlines()
    reqs.extend(required)

params = {
    'data_files': [],
}

setup(name='crow',
    version='0.1',
    description='Parallel matrix factorization framework.',
    url='http://bitbucket.org/acopar/crow',
    author='Andrej Copar',
    license='LGPL',
    packages=find_packages(),
    entry_points = {
        "console_scripts": ['crow = crow.__main__:main',
                            'crow-runner = crow.__main__:run',
                            'crow-test = tests.__main__:main',
                            'crow-conv = crow.convert.__main__:main']
    },
    zip_safe=False,
    install_requires=reqs,
    **params
)

