# Autogenerated config file using crow.conf
VERSION = '0.1'
IMG = '/home/crow/crow/../img'
DATA = '/home/crow/crow/../data'
STORAGE = '/home/crow/crow/../storage'
CACHE = '/home/crow/crow/../cache'
RESULTS = '/home/crow/crow/../results'

