# Autogenerated config file using crow.conf
VERSION = '0.1'
IMG = '/home/mpirun/crow/../img'
DATA = '/home/mpirun/crow/../data'
STORAGE = '/home/mpirun/crow/../storage'
CACHE = '/home/mpirun/crow/../cache'
RESULTS = '/home/mpirun/crow/../results'

