#!/bin/bash

function run_gpu {
    if [[ $(which crow-nvidia-version) ]]; then
        vscript="crow-nvidia-version"
        VOLUME=$(crow-nvidia-version)
    elif [ -e "scripts/nvidia_get_volume.py" ]; then
        vscript="scripts/nvidia_get_volume.py"
        VOLUME=$(python $vscript)
    else
        echo "Volume query script not found"
        echo "Try running scripts/install-crow.sh"
    fi
    
    if [[ -z "$VOLUME" ]]; then
        echo -n "Write nvidia driver version (ex. 367.57), empty to abort: "
        read version
        if [ -z "$version" ]; then
            exit
        fi
        VOLUME="nvidia_driver_$version"
    fi
    
    if [ -z $VOLUME ]; then
        echo "No nvidia volume found"
        echo "Perhaps nvidia-docker-plugin is not running?"
        exit 0
    fi
    
    has_volume=$(docker volume ls | grep $VOLUME | wc -l)
    if [ $has_volume -eq 0 ]; then
        echo "Creating volume $VOLUME..."
        docker volume create -d nvidia-docker --name=$VOLUME
    fi
    
    nvidia-docker-compose up $*
}

function run_cpu {
    docker-compose up $*
}

if [ -e /dev/nvidiactl ]; then
    run_gpu $*
else
    run_cpu $*
fi
