#!/bin/bash

crow-set-uid

context=$1
runtime='--runtime='

if [[ "$context" == "cpu" ]]; then
    # Force CPU-only
    runtime='--runtime='
elif [[ "$context" == "gpu" || -e /dev/nvidiactl ]]; then
    runtime='--runtime=nvidia'
fi

existing=$(docker ps -a -q --filter name="^/crow$")
if [ ! -z "$existing" ]; then
    docker rm "$existing"
fi

# Create mount points
if [ ! -d data ]; then
    mkdir data
fi
if [ ! -d cache ]; then
    mkdir cache
fi
if [ ! -d results ]; then
    mkdir results
fi


docker run -d $runtime --name="crow" -p 22 -v $PWD/crow:/home/crow/crow -v $PWD/data:/home/crow/data:ro -v $PWD/cache:/home/crow/cache -v $PWD/results:/home/crow/results --rm acopar/crow

